### PR TITLE
feat: add exclude option

### PR DESCRIPTION
**Pull request by endday**
I create a new pull request about the exclude.
Could you please spent some times to review the code.
Waiting for your reply，thank you.

### CODE REVIEW

**Comment by endday** [comment]
Does anyone review this request?
This new feature is important for me.

**Comment by dbox** [comment]
bump. would love to see this too

**Comment by cuth** [comment]
@endday Thank you for your Pull Request. Sorry for such a long delay in a response!

This is interesting. I figured that in whatever system you used this plugin in, that system would allow you to choose what file to run it on and what files to ignore. To me it seems like a bad pattern to make the plugins have their own way of ignoring files. If that was the case then all the plugin creators should come together and come up with some kind of standard option that everyone should add. See what I'm getting at? Most people use several PostCSS plugins with this plugin and it would be complicated if you had to learn each plugins system to ignore the correct files.

Can you help me understand why someone would need this?

**Comment by leereichardt** [comment]
We have multiple entries in our Webpack config, I only want to convert to rem in 1 of those entry points while leaving the other these as fixed pixels. I guess this could be done using multiple rules in the Webpack config, but then you have duplicate code sitting around

**Comment by EvanLiu2968** [comment]
when my project need pxtorem, but some components libs should be excluded, the exclude option would be usefull.

**Comment by cuth** [comment]
I changed my mind. I want to include this. Would you like to resolve the conflicts or else I can take these changes and apply them to a new branch?

FYI, I just added eslint and prettier to the package so it is easier to get the formatting correct.

**Comment by endday** [comment]
我太久没有看过这个项目了，所以代码都不太理解了，在解决冲突上花了比较久的时间。
这合并请求还有进展，让我十分惊喜，希望这个功能能给使用者带来方便。
————————————————————————————————————————————
I haven't seen this project for a long time, so I don't understand the code very much, and I spent a long time in resolving conflicts.

I am very surprised by the progress of this merge request. I hope this function will bring convenience to users.

**Comment by cuth** [comment]
Thanks!

**Comment by cuth** [comment]
This is published as 5.1.0

**Pull request merged**
