### PR TITLE
feat: change rootValue to support both number and function

### PR DESCRIPTION
**Pull request by johvin**
change rootValue to support function type in order to make it possible to get different root values based on different files

### CODE REVIEW

**Comment by johvin** [comment]
@cuth  Do you have any time to review this pr?

**Comment by johvin** [comment]
@cuth I also have very little free time  because of a lot of business to do. Although I may not be very helpful, but we can have a try.

**Comment by MillionQW** [comment]
I hope this feat can publish to npm.

**Comment by cuth** [comment]
I just published 5.0.0

**Pull request merged**
