### PR TITLE
Allow whitelisting of all properties

### PR DESCRIPTION
**Pull request by sndrs**
I'd like to switch to use this in gulp from grunt on The Guardian, but currently we expect to remify all units. This PR would to enable that with `prop_white_list: 'all'`. 

This could be particularly useful used with the new `selectorBlackList`. 

Incidentally, interested to know why you didn't want to whitelist all props by default?

### CODE REVIEW

**Comment by cuth** [comment]
Do you have any problem with us changing this to check if the prop_white_list array is empty then don't filter using the prop_white_list?

```js
if (propWhiteList.length && propWhiteList.indexOf(decl.prop) === -1) return;
```

I personally only found it useful to convert font related units to REM but I'm happy to see people are finding other good uses.

**Comment by sndrs** [comment]
nope, none at all, that's nicer actually. i'll amend the PR…

**Comment by sndrs** [comment]
this will introduce a breaking change i guess though? the defaults will no longer be present. how do you feel about that?

**Comment by cuth** [comment]
I think that makes sense to default to empty array. Breaking change it is.

**Comment by cuth** [comment]
I've taken your suggestions and released them in 2.3.0. I didn't change the defaults so as not to make a breaking change. Sorry I didn't use your pull request. Thank you for your help. Feel free to submit more PRs or ideas.

**Pull request closed without merging**
